[build]
  command = "gatsby build"
  publish = "public"
[build.environment]
  NODE_VERSION = "12.13.0"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
[context.storybook]
  command = "npm run build-storybook"
  publish = "storybook"
